Create model
Victoria-Kravets/proveng2 pull request #2
Opened 2017-08-22 20:45 UTC by Victoria-Kravets

2017-08-22 21:20 UTC, mmisesin approved these changes

2017-08-23 08:57 UTC, PavloNikytynskyi requested changes

2017-08-23 08:57 UTC, pnikitinsky commented on proveng2/Models/User.swift
> +class User: Object, Mappable {
StaticMappable мне позволило не использовать init, мапить в бекграунде

2017-08-23 08:57 UTC, pnikitinsky commented on proveng2/Models/User.swift
> +        self.init()
Вместо инита тогда сможем использовать 
class func objectForMapping(map: Map) -> BaseMappable? {
        return User()
    }

2017-08-23 08:57 UTC, pnikitinsky commented on proveng2/Models/User.swift
> +        self.init()
ListTransform заточен под StaticMappable, помоему....

2017-08-23 08:57 UTC, pnikitinsky commented on proveng2/ListTransform.swift
> +class ListTransform<T: RealmSwift.Object>: TransformType where T:Mappable {
where T: StaticMappable

2017-08-23 11:29 UTC, PavloNikytynskyi approved these changes

2017-08-23 14:56 UTC, merged